In [1]:
# comment
print('hello')

hello

In [45]:
import pandas as pd

df = pd.read_csv('scount_2020_06_15-v2.csv')
df.created_at = pd.to_datetime(df.created_at, utc=True)
df.index = pd.DatetimeIndex(df.created_at, name="created_at")
df.index = df.index.tz_convert('Asia/Tokyo')

df.
df.head()

,created_at,is_interested,name,type,expired_on,start_on,description,created_at1,family_name,first_name,confirmed_at,history,appeal,interest
created_at,,,,,,,,,,,,,,
2016-07-31 20:05:00+09:00,2016-07-31 11:05:00+00:00,0.0,TRUNK株式会社,PlatinumTicket,31/07/16,31/07/16,> 株式会社プリセプト 鈴木と申します。\r\n> \r\n> 貴殿のプロジェクト及びご経験...,31/07/16 11:05,澤村,直道,16/09/15 08:10,あ,NaN,あ
2016-04-08 20:40:00+09:00,2016-04-08 11:40:00+00:00,1.0,TRUNK株式会社,PlatinumTicket,04/08/16,04/08/16,はじめまして、TRUNKの代表の西元と申します。\r\n原さんの「実績・活動」を拝見し、是非...,04/08/16 11:40,原,亜依南,20/08/15 04:35,HR領域でのインターン,株式会社HERPというスタートアップで採用コンサルタントのインターンをしています。\r\n採...,カスタマーサクセス
2016-04-08 21:18:00+09:00,2016-04-08 12:18:00+00:00,0.0,TRUNK株式会社,PlatinumTicket,04/08/16,04/08/16,はじめまして、TRUNKの代表の西元と申します。\r\n原さんの「スキル・実績」を拝見し、是...,04/08/16 12:18,原,亜依南,20/08/15 04:35,HR領域でのインターン,株式会社HERPというスタートアップで採用コンサルタントのインターンをしています。\r\n採...,カスタマーサクセス
2016-08-19 18:42:00+09:00,2016-08-19 09:42:00+00:00,1.0,TRUNK株式会社,PlatinumTicket,19/08/16,19/08/16,はじめまして、TRUNK代表の西元と申します。\r\n◉◉さんの「スキル・実績」を拝見し、是...,19/08/16 09:42,澤村,直道,16/09/15 08:10,あ,NaN,あ
2017-02-03 17:14:00+09:00,2017-02-03 08:14:00+00:00,0.0,TRUNK株式会社,VisitTicket,02/07/17,02/03/17,後藤さん\n初めまして。\nTrunkで採用担当をしております、原と申します。\nいつもTR...,02/03/17 08:14,後藤,宏毅,25/10/16 07:13,iOS開発,BBT大学経営学部ITソリューション学科3年。21歳。\r\nめっちゃ牛乳好き。,rails

In [46]:
from datetime import time

print(len(df))

time1 = df.between_time(time(9, 0),time(12, 0))
print('time1', len(time1),  (time1['is_interested'] == 1.0).sum())

time2 = df.between_time(time(12, 0),time(15, 0))
print('time2', len(time2),  (time2['is_interested'] == 1.0).sum())

time3 = df.between_time(time(15, 0),time(18, 0))
print('time3', len(time3),  (time3['is_interested'] == 1.0).sum())

time4 = df.between_time(time(18, 0),time(21, 0))
print('time4', len(time4),  (time4['is_interested'] == 1.0).sum())

time5 = df.between_time(time(21, 0),time(0, 0))
print('time5', len(time5),  (time5['is_interested'] == 1.0).sum())

time6 = df.between_time(time(0, 0),time(9, 0))
print('time6', len(time6),  (time6['is_interested'] == 1.0).sum())

3520
time1 1144 222
time2 728 160
time3 807 168
time4 562 80
time5 226 28
time6 76 11

In [65]:
df['day'] = df.index.day_name()
df.head()

mon = df[df.index.weekday == 0]
print('mon', len(mon), (mon['is_interested'] == 1.0).sum())

tue = df[df.index.weekday == 1]
print('tue', len(tue), (tue['is_interested'] == 1.0).sum())


wed = df[df.index.weekday == 2]
print('wed', len(wed), (wed['is_interested'] == 1.0).sum())

thu = df[df.index.weekday == 3]
print('thu', len(thu), (thu['is_interested'] == 1.0).sum())

fri= df[df.index.weekday == 4]
print('fri', len(fri), (fri['is_interested'] == 1.0).sum())

sat = df[df.index.weekday == 5]
print('sat', len(sat), (sat['is_interested'] == 1.0).sum())

sun = df[df.index.weekday == 6]
print('sun', len(sun), (sun['is_interested'] == 1.0).sum())

mon 573 127
tue 540 121
wed 580 112
thu 744 139
fri 454 65
sat 368 53
sun 261 48